#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

INDEX_FILE="agent-docs/index.md"
GENERATED_DIR="agent-docs/generated"
INVENTORY_FILE="$GENERATED_DIR/doc-inventory.md"
REPORT_FILE="$GENERATED_DIR/doc-gardening-report.md"

fail_on_issues=0
if [[ "${1:-}" == "--fail-on-issues" ]] || [[ "${FAIL_ON_DOC_ISSUES:-0}" == "1" ]]; then
  fail_on_issues=1
fi

if [[ ! -f "$INDEX_FILE" ]]; then
  echo "Missing $INDEX_FILE"
  exit 1
fi

mkdir -p "$GENERATED_DIR"

tracked_docs="$({
  find agent-docs -type f -name '*.md' \
    ! -path 'agent-docs/index.md' \
    ! -path 'agent-docs/generated/doc-inventory.md' \
    ! -path 'agent-docs/generated/doc-gardening-report.md'
} | sort -u)"

indexed_paths="$({
  awk -F'`' '/^\|/ && $2 ~ /^agent-docs\// {print $2}' "$INDEX_FILE"
  awk -F'`' '/^\|/ && $2 ~ /^ARCHITECTURE\.md$/ {print $2}' "$INDEX_FILE"
} | sort -u || true)"

is_doc_indexed() {
  local doc_path="$1"
  while IFS= read -r indexed; do
    [[ -z "$indexed" ]] && continue
    if [[ "$indexed" == */ ]]; then
      [[ "$doc_path" == "$indexed"* ]] && return 0
    else
      [[ "$doc_path" == "$indexed" ]] && return 0
    fi
  done <<< "$indexed_paths"
  return 1
}

unindexed_docs=()
while IFS= read -r doc; do
  [[ -z "$doc" ]] && continue
  if ! is_doc_indexed "$doc"; then
    unindexed_docs+=("$doc")
  fi
done <<< "$tracked_docs"

missing_index_targets=()
while IFS= read -r indexed; do
  [[ -z "$indexed" ]] && continue
  if [[ "$indexed" == */ ]]; then
    if [[ ! -d "${indexed%/}" ]]; then
      missing_index_targets+=("$indexed")
    fi
  else
    if [[ ! -f "$indexed" ]]; then
      missing_index_targets+=("$indexed")
    fi
  fi
done <<< "$indexed_paths"

{
  echo "# Agent Docs Inventory"
  echo
  echo "Auto-generated by scripts/doc-gardening.sh."
  echo
  echo "## Tracked Artifacts (.md)"
  if [[ -n "$tracked_docs" ]]; then
    while IFS= read -r doc; do
      [[ -z "$doc" ]] && continue
      printf -- '- `%s`\n' "$doc"
    done <<< "$tracked_docs"
  else
    echo "- None"
  fi
} > "$INVENTORY_FILE"

{
  echo "# Agent Doc Gardening Report"
  echo
  echo "Auto-generated by scripts/doc-gardening.sh."
  echo
  echo "## Unindexed Tracked Artifacts"
  if (( ${#unindexed_docs[@]} == 0 )); then
    echo "- None"
  else
    for doc in "${unindexed_docs[@]}"; do
      printf -- '- `%s`\n' "$doc"
    done
  fi
  echo
  echo "## Broken Index Targets"
  if (( ${#missing_index_targets[@]} == 0 )); then
    echo "- None"
  else
    for target in "${missing_index_targets[@]}"; do
      printf -- '- `%s`\n' "$target"
    done
  fi
} > "$REPORT_FILE"

issue_count=$(( ${#unindexed_docs[@]} + ${#missing_index_targets[@]} ))
echo "Doc gardening completed. Issues found: $issue_count"

if (( fail_on_issues == 1 )) && (( issue_count > 0 )); then
  echo "Doc gardening found issues and fail-on-issues is enabled."
  exit 1
fi
